language: python
python:
  - "3.8"

addons:
  chrome: stable
  firefox: latest

# safelist
branches:
  only:
    - develop

# stuff to do before executing the script
install:
    # command to install dependencies
  - pip install -r requirements.txt
  - pip install tchappui-webdrivers

before_script:
  - install-webdrivers

env: 
  global:
    - DJANGO_SETTINGS_MODULE=config.settings.travis

services:
  - postgresql

script:
  - ./manage.py test tests


