language: python
python:
  - "3.8"

addons:
  chrome: stable
  firefox: latest

# safelist
branches:
  only:
    - develop
    - main

# stuff to do before executing the script
install:
    # command to install dependencies
  - pip install -r requirements.txt
  - pip install tchappui-webdrivers

before_script:
  - install-webdrivers

env:
  global:
    - ENV=travis
    - MOZ_HEADLESS=1

services:
  - postgresql

script:
  - python3 manage.py test tests
